env:
  global:
    - CC_TEST_REPORTER_ID=bbaf5cc143bd1392a499ae06259d1fb02d506669eff4f73acc837f75410cc01c
language: node_js
node_js:
  - node
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
  - npm install -g jest
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT